// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'persistence/stored_generation_config.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 3310038345540877913),
    name: 'StoredGenerationConfig',
    lastPropertyId: const obx_int.IdUid(7, 6345784816089124492),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1062414593896946713),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5670889088870919135),
        name: 'name',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(1, 2661164549898354312),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4020625123244627954),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3624904657494949648),
        name: 'version',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4952129575768967067),
        name: 'tagsJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3054512042631581656),
        name: 'configJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6345784816089124492),
        name: 'updatedAtEpochMs',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 3310038345540877913),
    lastIndexId: const obx_int.IdUid(1, 2661164549898354312),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    StoredGenerationConfig: obx_int.EntityDefinition<StoredGenerationConfig>(
      model: _entities[0],
      toOneRelations: (StoredGenerationConfig object) => [],
      toManyRelations: (StoredGenerationConfig object) => {},
      getId: (StoredGenerationConfig object) => object.id,
      setId: (StoredGenerationConfig object, int id) {
        object.id = id;
      },
      objectToFB: (StoredGenerationConfig object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final descriptionOffset = fbb.writeString(object.description);
        final tagsJsonOffset = fbb.writeString(object.tagsJson);
        final configJsonOffset = fbb.writeString(object.configJson);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, descriptionOffset);
        fbb.addInt64(3, object.version);
        fbb.addOffset(4, tagsJsonOffset);
        fbb.addOffset(5, configJsonOffset);
        fbb.addInt64(6, object.updatedAtEpochMs);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final versionParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final tagsJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final configJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final updatedAtEpochMsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final object = StoredGenerationConfig(
          id: idParam,
          name: nameParam,
          description: descriptionParam,
          version: versionParam,
          tagsJson: tagsJsonParam,
          configJson: configJsonParam,
          updatedAtEpochMs: updatedAtEpochMsParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [StoredGenerationConfig] entity fields to define ObjectBox queries.
class StoredGenerationConfig_ {
  /// See [StoredGenerationConfig.id].
  static final id = obx.QueryIntegerProperty<StoredGenerationConfig>(
    _entities[0].properties[0],
  );

  /// See [StoredGenerationConfig.name].
  static final name = obx.QueryStringProperty<StoredGenerationConfig>(
    _entities[0].properties[1],
  );

  /// See [StoredGenerationConfig.description].
  static final description = obx.QueryStringProperty<StoredGenerationConfig>(
    _entities[0].properties[2],
  );

  /// See [StoredGenerationConfig.version].
  static final version = obx.QueryIntegerProperty<StoredGenerationConfig>(
    _entities[0].properties[3],
  );

  /// See [StoredGenerationConfig.tagsJson].
  static final tagsJson = obx.QueryStringProperty<StoredGenerationConfig>(
    _entities[0].properties[4],
  );

  /// See [StoredGenerationConfig.configJson].
  static final configJson = obx.QueryStringProperty<StoredGenerationConfig>(
    _entities[0].properties[5],
  );

  /// See [StoredGenerationConfig.updatedAtEpochMs].
  static final updatedAtEpochMs =
      obx.QueryIntegerProperty<StoredGenerationConfig>(
        _entities[0].properties[6],
      );
}
